POST http://localhost:4406/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI2NzU3MjE2LCJ1c2VySWQiOjJ9.fybvyKljiFnREscFcX9NJyNH0ssPm-54wmT-qVDurxw

